### ISSUE TITLE
Error: Chromium revision is not downloaded

### ISSUE THREAD

**Issue by kachkaev** [urlint/urlint#100]
I just came across this package and decided to give it a go. Seems like there is an issue following the bump of Puppeteer in [adblocker](https://github.com/cliqz-oss/adblocker/releases)@1.4.0. Reproduction steps on macOS (Node 12):

```
npm install urlint -g

/usr/local/bin/urlint -> /usr/local/lib/node_modules/urlint/bin/cli/index.js
npm WARN @cliqz/adblocker-puppeteer@1.4.0 requires a peer of puppeteer@^2.0.0 but none is installed. You must install peer dependencies yourself.

+ urlint@1.8.5
```

```
urlint example.com
42.4s ⠹  ← timer keeps ticking forever

ctrl+c ↓

Error: Chromium revision is not downloaded. Run "npm install" or "yarn install"
    at Launcher.launch (/usr/local/lib/node_modules/urlint/node_modules/puppeteer-core/lib/Launcher.js:119:15)
    at async pRetry.onFailedAttempt.debug.attemptNumber (/usr/local/lib/node_modules/urlint/node_modules/browserless/src/index.js:35:26)
    at async RetryOperation._fn (/usr/local/lib/node_modules/urlint/node_modules/p-retry/index.js:41:12)
Error: Chromium revision is not downloaded. Run "npm install" or "yarn install"
    at Launcher.launch (/usr/local/lib/node_modules/urlint/node_modules/puppeteer-core/lib/Launcher.js:119:15)
    at async pRetry.onFailedAttempt.debug.attemptNumber (/usr/local/lib/node_modules/urlint/node_modules/browserless/src/index.js:35:26)
    at async RetryOperation._fn (/usr/local/lib/node_modules/urlint/node_modules/p-retry/index.js:41:12)
Error: Chromium revision is not downloaded. Run "npm install" or "yarn install"
    at Launcher.launch (/usr/local/lib/node_modules/urlint/node_modules/puppeteer-core/lib/Launcher.js:119:15)
    at async pRetry.onFailedAttempt.debug.attemptNumber (/usr/local/lib/node_modules/urlint/node_modules/browserless/src/index.js:35:26)
    at async RetryOperation._fn (/usr/local/lib/node_modules/urlint/node_modules/p-retry/index.js:41:12)
Error: Chromium revision is not downloaded. Run "npm install" or "yarn install"
    at Launcher.launch (/usr/local/lib/node_modules/urlint/node_modules/puppeteer-core/lib/Launcher.js:119:15)
    at async pRetry.onFailedAttempt.debug.attemptNumber (/usr/local/lib/node_modules/urlint/node_modules/browserless/src/index.js:35:26)
    at async RetryOperation._fn (/usr/local/lib/node_modules/urlint/node_modules/p-retry/index.js:41:12)
Error: Chromium revision is not downloaded. Run "npm install" or "yarn install"
    at Launcher.launch (/usr/local/lib/node_modules/urlint/node_modules/puppeteer-core/lib/Launcher.js:119:15)
    at async pRetry.onFailedAttempt.debug.attemptNumber (/usr/local/lib/node_modules/urlint/node_modules/browserless/src/index.js:35:26)
    at async RetryOperation._fn (/usr/local/lib/node_modules/urlint/node_modules/p-retry/index.js:41:12)
```

**Comment by Kikobeats** [comment]
That's probably because I updated the dependencies but I don't bump a new urlint version.

I just released `urlint@1.8.6` and it's working fine to me:

```bash
❯ npm install urlint -g
/usr/local/bin/urlint -> /usr/local/lib/node_modules/urlint/bin/cli/index.js

> sharp@0.23.4 install /usr/local/lib/node_modules/urlint/node_modules/sharp
> (node install/libvips && node install/dll-copy && prebuild-install) || (node-gyp rebuild && node install/dll-copy)

info sharp Using cached /Users/josefranciscoverdugambin/.npm/_libvips/libvips-8.8.1-darwin-x64.tar.gz

> puppeteer-core@2.0.0 install /usr/local/lib/node_modules/urlint/node_modules/puppeteer-core
> node install.js


> @browserless/goto@5.18.12 postinstall /usr/local/lib/node_modules/urlint/node_modules/@browserless/goto
> node scripts/postinstall


> top-sites@1.1.13 postinstall /usr/local/lib/node_modules/urlint/node_modules/top-sites
> node scripts/postinstall


> html-get@2.2.30 postinstall /usr/local/lib/node_modules/urlint/node_modules/html-get
> node scripts/postinstall

npm WARN @cliqz/adblocker-puppeteer@1.4.0 requires a peer of puppeteer@^2.0.0 but none is installed. You must install peer dependencies yourself.

+ urlint@1.8.6
added 204 packages from 184 contributors and updated 307 packages in 58.157s

~/Downloads 59s
❯ urlint https://microlink.io

2xx 27
3xx 16

43 links in 4.3s
```

Can you try now? 🙂

**Comment by Kikobeats** [comment]
Closing until it happens again

**Comment by kachkaev** [comment]
The latest version seems to work. Thanks for the patch @Kikobeats 🙌

**Comment by Kikobeats** [comment]
Awesome! What do you think about the project?

**Comment by kachkaev** [comment]
Looks interesting and the website is neat. I might urlint for one side project in CI/CD ;)

Thanks for your work!
