### ISSUE TITLE
Cannot read property 'toString' of undefined

### ISSUE THREAD

**Issue by paulomanrique** [urlint/urlint#103]
When I try to run on http://www.rdias.com.br I get the following error, after it verified some of the urls:

TypeError: Cannot read property 'toString' of undefined
    at getStatusCodeId (/home/paulo/.npm-packages/lib/node_modules/urlint/bin/view/colorize.js:13:50)
    at getStatusCodeColor (/home/paulo/.npm-packages/lib/node_modules/urlint/bin/view/colorize.js:16:14)
    at byStatusCode (/home/paulo/.npm-packages/lib/node_modules/urlint/bin/view/colorize.js:21:17)
    at renderLink (/home/paulo/.npm-packages/lib/node_modules/urlint/bin/view/render.js:29:44)
    at /home/paulo/.npm-packages/lib/node_modules/urlint/bin/view/render.js:48:19
    at arrayMap (/home/paulo/.npm-packages/lib/node_modules/urlint/node_modules/lodash/lodash.js:639:23)
    at map (/home/paulo/.npm-packages/lib/node_modules/urlint/node_modules/lodash/lodash.js:9554:14)
    at /home/paulo/.npm-packages/lib/node_modules/urlint/bin/view/render.js:36:18
    at /home/paulo/.npm-packages/lib/node_modules/urlint/node_modules/lodash/lodash.js:3543:27
    at /home/paulo/.npm-packages/lib/node_modules/urlint/node_modules/lodash/lodash.js:4905:15

**Comment by Kikobeats** [comment]
Hum, that sounds a bit strange

<img width="428" alt="Screenshot 2020-01-22 at 11 12 56" src="https://user-images.githubusercontent.com/2096101/72885426-2cddfd80-3d08-11ea-9a9c-f81792cca4d3.png">

Are you using the latest urlint version?
What version of Node are you using?

**Comment by Kikobeats** [comment]
oh I detected the bug, let me fix it and ship a new version

**Comment by Kikobeats** [comment]
@paulomanrique I think the bug is fixed.

I shipped `urlint@1.9.0`, can you test if it's working fine now?

```
npx urlint http://www.rdias.com.br
```

**Comment by paulomanrique** [comment]
It's perfect now, thanks man! :)
